baseURL = 'https://byungkwonc.github.io/'
languageCode = 'en-us'
title = "byungkwonc's blog"
theme = "hugo-theme-docport"
googleAnalytics = "G-X4VJXS86CB"
pygmentsCodeFences = true
pygmentsUseClasses = true
lastmod = true
pin = true
mathJax = true

[[menu.shortcuts]]
name = "Github"
identifier = "ds"
url = "https://github.com/byungkwonc"
weight = 10

[[menu.shortcuts]]
name = "Download"
url = "https://github.com/byungkwonc/byungkwonc.github.io/archive/refs/tags/v0.1.zip"
weight = 11

[[menu.shortcuts]]
name = "Hugo Documentation"
identifier = "hugodoc"
url = "https://gohugo.io/"
weight = 20

[frontmatter]
  lastmod = ["lastmod", ":fileModTime", ":default"]
  katex = "math"
